security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_MARKETEUR: ROLE_MARKETEUR
        ROLE_COMMERCIAL: ROLE_COMMERCIAL
        ROLE_RECOUVREUR: ROLE_RECOUVREUR


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
#                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                success_handler: redirect.after.login
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: /recouvreur, role: ROLE_RECOUVREUR }
        - { path: /commercial, role: ROLE_COMMERCIAL }
        - { path: /marketeur, role: ROLE_MARKETEUR }