<?php

namespace Recouvrement\AmiableBundle\Repository;

/**
 * mytestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class mytestRepository extends \Doctrine\ORM\EntityRepository
{
}
